### ISSUE TITLE
relative imports do not work

### ISSUE THREAD

**Issue by gugundi** [tomerwolgithub/Break#1]
In qdmr_parsing:

After running preprocessing, when trying to run any of the evaluation commands, I get the following error: "ModuleNotFoundError: No module named 'evaluation'".
It has the same error on all of the following lines (8-11) in run_model():

from evaluation.decomposition import Decomposition, get_decomposition_from_tokens
from model.rule_based.rule_based_model import RuleBasedModel
from model.rule_based.copy_model import CopyModel
from model.seq2seq.seq2seq_model import Seq2seqModel

**Comment by mega002** [comment]
You should add the qdmr_parsing directory to the PYTHONPATH environment variable.
For example, on Linux this can be done by running the following command from this directory:
`export PYTHONPATH=${PYTHONPATH}:`pwd``

**Comment by gugundi** [comment]
I have already tried this, and it didn't work
