### ISSUE TITLE
Nan loss during training copynet

### ISSUE THREAD

**Issue by saparina** [tomerwolgithub/Break#11]
Hi, I'm trying to reproduce your results, but during training copynet model I'm getting the error with nan loss:
```
Traceback (most recent call last):
  File "/home/isaparina/miniconda3/envs/break_models/bin/allennlp", line 8, in <module>
    sys.exit(run())
  File "/home/isaparina/miniconda3/envs/break_models/lib/python3.6/site-packages/allennlp/run.py", line 18, in run
    main(prog="allennlp")
  File "/home/isaparina/miniconda3/envs/break_models/lib/python3.6/site-packages/allennlp/commands/__init__.py", line 101, in main
    args.func(args)
  File "/home/isaparina/miniconda3/envs/break_models/lib/python3.6/site-packages/allennlp/commands/train.py", line 103, in train_model_from_args
    args.force)
  File "/home/isaparina/miniconda3/envs/break_models/lib/python3.6/site-packages/allennlp/commands/train.py", line 136, in train_model_from_file
    return train_model(params, serialization_dir, file_friendly_logging, recover, force)
  File "/home/isaparina/miniconda3/envs/break_models/lib/python3.6/site-packages/allennlp/commands/train.py", line 204, in train_model
    metrics = trainer.train()
  File "/home/isaparina/miniconda3/envs/break_models/lib/python3.6/site-packages/allennlp/training/trainer.py", line 480, in train
    train_metrics = self._train_epoch(epoch)
  File "/home/isaparina/miniconda3/envs/break_models/lib/python3.6/site-packages/allennlp/training/trainer.py", line 325, in _train_epoch
    raise ValueError("nan loss encountered")
ValueError: nan loss encountered
```
This error occurs after using the config [from repo](https://github.com/tomerwolgithub/Break/blob/master/qdmr_parsing/model/seq2seq/train-seq2seq-copynet.json) and the config [available with pretrained models](https://storage.googleapis.com/ai2i/break_models/seq2seq-copynet_layers2_lr0.001_hd450_dop0.2_final_low.zip). Training seq2seq and dynamic was ok. 
I installed the required packages and followed the instructions described in #4.

What are the possible reasons for this problem? Thanks!

**Comment by tomerwolgithub** [comment]
Hi @saparina , so you are trying to train the Copynet model on the low-level break data using our pretrained model config, right? 
Could you please provide us with the following details on your environment:  OS, installed python packages, the command executed, and whether you are running on CPU/GPU. 
Thanks!

**Comment by saparina** [comment]
Yes, I used low-level break data. I am running on GPU using command
` allennlp train -s copynet/ ./data/seq2seq-copynet_layers2_lr0.001_hd450_dop0.2_final_low/config.json`

OS: CentOS Linux 7 (Core)
Python 3.6.8
Installed python packages:
```
Package                       Version
----------------------------- -------------------
alabaster                     0.7.12
allennlp                      0.8.3
attrs                         19.3.0
aws-sam-translator            1.25.0
aws-xray-sdk                  2.6.0
awscli                        1.18.106
Babel                         2.8.0
blis                          0.2.4
boto                          2.49.0
boto3                         1.14.29
botocore                      1.17.29
certifi                       2020.6.20
cffi                          1.14.1
cfn-lint                      0.34.0
chardet                       3.0.4
click                         7.1.2
colorama                      0.4.3
conllu                        0.11
cryptography                  3.0
cycler                        0.10.0
cymem                         2.0.3
decorator                     4.4.2
docker                        4.2.2
docutils                      0.15.2
ecdsa                         0.15
edit-distance                 1.0.3
editdistance                  0.5.3
en-core-web-sm                2.1.0
flaky                         3.7.0
Flask                         1.1.2
Flask-Cors                    3.0.8
ftfy                          5.8
future                        0.18.2
gevent                        20.6.2
greenlet                      0.4.16
h5py                          2.10.0
idna                          2.10
imagesize                     1.2.0
importlib-metadata            1.7.0
importlib-resources           1.5.0
itsdangerous                  1.1.0
Jinja2                        2.11.2
jmespath                      0.10.0
joblib                        0.16.0
jsondiff                      1.1.2
jsonnet                       0.16.0
jsonpatch                     1.26
jsonpickle                    1.4.1
jsonpointer                   2.0
jsonschema                    2.6.0
junit-xml                     1.9
kiwisolver                    1.2.0
MarkupSafe                    1.1.1
matplotlib                    3.3.0
mock                          4.0.2
more-itertools                8.4.0
moto                          1.3.14
msgpack                       0.5.6
murmurhash                    1.0.2
networkx                      2.3
neuralcoref                   4.0
nltk                          3.5
numpy                         1.19.1
numpydoc                      1.1.0
overrides                     3.1.0
packaging                     20.4
pandas                        0.24.2
parsimonious                  0.8.1
Pillow                        7.2.0
pip                           20.1.1
plac                          0.9.6
pluggy                        0.13.1
preshed                       2.0.1
progressbar                   2.5
protobuf                      3.12.2
py                            1.9.0
pyasn1                        0.4.8
pycparser                     2.20
Pygments                      2.6.1
pyparsing                     2.4.7
pytest                        5.4.3
python-dateutil               2.8.1
python-jose                   3.1.0
pytorch-pretrained-bert       0.6.2
pytz                          2020.1
PyYAML                        5.3.1
regex                         2020.7.14
requests                      2.24.0
responses                     0.10.15
rsa                           4.5
s3transfer                    0.3.3
scikit-learn                  0.22.2
scipy                         1.5.2
setuptools                    49.2.0.post20200714
six                           1.15.0
snowballstemmer               2.0.0
spacy                         2.1.3
Sphinx                        3.1.2
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        1.0.3
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.4
sqlparse                      0.3.1
srsly                         1.0.2
sshpubkeys                    3.1.0
tensorboardX                  2.1
thinc                         7.0.8
threadpoolctl                 2.1.0
torch                         1.5.1
tqdm                          4.48.0
Unidecode                     1.1.1
urllib3                       1.25.10
wasabi                        0.7.1
wcwidth                       0.2.5
websocket-client              0.57.0
Werkzeug                      1.0.1
wheel                         0.34.2
word2number                   1.1
wrapt                         1.12.1
xmltodict                     0.12.0
zipp                          3.1.0
zope.event                    4.4
zope.interface                5.1.0
```

**Comment by tomerwolgithub** [comment]
Great, thanks.
Please try using the following command for training:
`python -m allennlp.run train model/seq2seq/train-seq2seq-copynet.json -s tmp/seq2seq-copynet_layers2_lr0.001_hd450_dop0.2_final_low -o "{train_data_path: 'data/train_final_low.tsv', validation_data_path: 'data/dev_final_low.tsv', test_data_path: 'data/test_final_low.tsv', trainer: { optimizer: {lr: 0.001} }, model: {source_embedder: {tokens: {embedding_dim: 450}} , encoder: {num_layers: 2, input_size: 450, hidden_size: 450, dropout: 0.2} }}"`

**Comment by saparina** [comment]
I tried this command, but the same error still occurs

**Comment by tomerwolgithub** [comment]
This is strange.. It might be an issue with the [older allennlp and pytorch](https://github.com/allenai/allennlp/issues/3232) versions. I'm currently using torch==1.1.0 along with allennlp==0.8.3 and it works fine. Perhaps downgrading pytorch to 1.1.0 should work. If so, we'll update the requirements accordingly.

**Comment by saparina** [comment]
Thank you for trying to help me. I still have the same problem even with Pytorch 1.1. I also got this error while running on CPU. 
Maybe the problem is somewhere in other packages. Could you please share your versions of the installed packages? I will try to reproduce your setup.

**Comment by tomerwolgithub** [comment]
Sure! 
The installed python packages:

`
alabaster==0.7.12
allennlp==0.8.3
atomicwrites==1.3.0
attrs==19.1.0
awscli==1.16.190
Babel==2.7.0
backcall==0.1.0
bleach==3.1.0
blis==0.2.4
boto3==1.9.180
botocore==1.12.180
certifi==2019.6.16
chardet==3.0.4
Click==7.0
colorama==0.3.9
conllu==0.11
cycler==0.10.0
cymem==2.0.2
decorator==4.4.0
defusedxml==0.6.0
docutils==0.14
edit-distance==1.0.3
editdistance==0.5.3
en-core-web-sm==2.1.0
entrypoints==0.3
flaky==3.6.0
Flask==1.0.3
Flask-Cors==3.0.8
ftfy==5.5.1
gevent==1.4.0
greenlet==0.4.15
h5py==2.9.0
idna==2.8
imagesize==1.1.0
importlib-metadata==0.18
ipykernel==5.1.1
ipython==7.6.0
ipython-genutils==0.2.0
itsdangerous==1.1.0
jedi==0.14.0
Jinja2==2.10.1
jmespath==0.9.4
joblib==0.13.2
json5==0.8.4
jsonnet==0.10.0
jsonpickle==1.2
jsonschema==2.6.0
jupyter-client==5.2.4
jupyter-core==4.5.0
jupyterlab==1.0.0
jupyterlab-server==1.0.0
kiwisolver==1.1.0
MarkupSafe==1.1.1
matplotlib==3.1.0
mistune==0.8.4
more-itertools==7.1.0
murmurhash==1.0.2
nbconvert==5.5.0
nbformat==4.4.0
networkx==2.4
neuralcoref==4.0
nltk==3.4.3
notebook==5.7.8
numpy==1.16.4
numpydoc==0.9.1
overrides==1.9
packaging==19.0
pandas==0.24.2
pandocfilters==1.4.2
parsimonious==0.8.1
parso==0.5.0
pexpect==4.7.0
pickleshare==0.7.5
plac==0.9.6
pluggy==0.12.0
preshed==2.0.1
progressbar==2.5
prometheus-client==0.7.1
prompt-toolkit==2.0.9
protobuf==3.8.0
ptyprocess==0.6.0
py==1.8.0
pyasn1==0.4.5
Pygments==2.4.2
pyparsing==2.4.0
pyrsistent==0.15.2
pytest==5.0.0
python-dateutil==2.8.0
pytorch-pretrained-bert==0.6.2
pytz==2019.1
PyYAML==5.1
pyzmq==18.0.2
regex==2019.6.8
requests==2.22.0
responses==0.10.6
rsa==3.4.2
s3transfer==0.2.1
scikit-learn==0.21.2
scipy==1.3.0
Send2Trash==1.5.0
six==1.12.0
sklearn==0.0
snowballstemmer==1.9.0
spacy==2.1.3
Sphinx==2.1.2
sphinxcontrib-applehelp==1.0.1
sphinxcontrib-devhelp==1.0.1
sphinxcontrib-htmlhelp==1.0.2
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.2
sphinxcontrib-serializinghtml==1.1.3
sqlparse==0.3.0
srsly==0.0.7
tensorboardX==1.7
terminado==0.8.2
testpath==0.4.2
thinc==7.0.4
torch==1.1.0
tornado==6.0.3
tqdm==4.32.2
traitlets==4.3.2
ujson==1.35
Unidecode==1.1.1
urllib3==1.25.3
wasabi==0.2.2
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.15.4
word2number==1.1
zipp==0.5.1
`

**Comment by saparina** [comment]
Thank you very much! I installed the packages with your versions and everything works fine now!
