### ISSUE TITLE
The evaluation takes a long time

### ISSUE THREAD

**Issue by SkyAndCloud** [tomerwolgithub/Break#12]
I have downloaded the pretrained `copynet_seq2seq` checkpoint, and want to evaluate on the dev set. However, I find the evaluation process takes a long time (several hours). Is there any problems in my script? Thanks

```
python model/run_model.py --input_file data/dev_copynet.tsv \
--preds_file copynet_ckpt/pretrained/seq2seq-copynet_layers2_lr0.001_hd450_dop0.2_final_low/dev_final_low_preds.json \
--model copynet \
--model_dir  copynet_ckpt/pretrained/seq2seq-copynet_layers2_lr0.001_hd450_dop0.2_final_low \
--evaluate \
--cuda_device 0 \
--num_processes 10
```

**Comment by tomerwolgithub** [comment]
Hi, there. The evaluation process takes some time when using the GED and GED+ evaluation metrics. GED uses a graph edit distance approximation algorithm to evaluate the distance between the graph representations of the gold & predicted QDMRs. Evaluating without the GED-based metrics (EM, SARI, etc.) would be faster.

**Comment by tomerwolgithub** [comment]
Btw, we also released an updated [Break evaluator](https://github.com/allenai/break-evaluator), used in our official leaderboard evaluation. In the evaluator you can directly specify which metics to using `--metrics`, e.g., `--metrics ged_scores exact_match sari normalized_exact_match `

**Comment by SkyAndCloud** [comment]
Thank you. I have a question that [Break evaluator](https://github.com/allenai/break-evaluator) takes the `csv` format as input, while the `copynet_seq2seq` outputs a `json` file. How to evaluate the metrics use Break evaluator?

**Comment by SkyAndCloud** [comment]
BTW, to make predictions on test set, whether use `allennlp predict ...` or use the `run_model.py` with `--evaluate` ?

**Comment by tomerwolgithub** [comment]
To generate predictions for the hidden test set you can use `run_model.py` without the `--evaluate` flag. As the gold QDMRs of the test set remain hidden, they are not supplied to the script during the data preprocessing phase.

**Comment by tomerwolgithub** [comment]
Regarding the previous message, you are right. The leadeboard evaluator takes as input a csv file of ordered predictions.
To convert the json results of our CopyNet model to standard QDMR format would require to covert the separator and delimiter tokens (`@@SEP@@`  to  `;` and `@@1@@` to `#1`).
