### ISSUE TITLE
Training COPYNET model

### ISSUE THREAD

**Issue by subhashiniy** [tomerwolgithub/Break#4]
Could you guide me in training a COPYNET model with qmdr dataset? 
I have gone through the repo many times and am unable to figure out how to train a model. 
Or are there pre-trained models available? 

Any help would he appreciated. 
Thanks!

**Comment by mega002** [comment]
As explained in the README file, training and running the neural models, including copynet, should be done with the AllenNLP framework.

To train them, you should execute a `train` [command](https://allennlp.org/api/commands/train/) and provide a configuration. You can find the configuration file we used for copynet [here](https://github.com/tomerwolgithub/Break/blob/master/qdmr_parsing/model/seq2seq/train-seq2seq-copynet.json). Note that the specific parameters we used are provided in the paper. 

When training is done, a `model.tar.gz` file will be created, which you can provide to the `run_model.py` script for evaluation.

I hope this helps.

**Comment by subhashiniy** [comment]
Thanks. When I initiated training using the command: 
`allennlp train seq2seq/train-seq2seq-copynet.json -s ./outputDir`

I am getting the error - 
`python3.6/site-packages/allennlp/data/dataset_readers/copynet_seq2seq.py", line 130, in _read
    raise RuntimeError("Invalid line format: %s (line number %d)" % (line, line_num + 1))
RuntimeError: Invalid line format: return me the homepage of PVLDB . 	['higher than', 'same as', 'what ', 'and ', 'than ', 'at most', 'distinct', 'two', 'at least', 'or ', 'date', 'on ', '@@14@@', 'equal', 'hundred', 'those', 'sorted by', 'elevation', 'which ', '@@6@@', 'was ', 'did ', 'population', 'height', 'one', 'that ', 'on', 'did', 'who', 'true', '@@2@@', '100', 'false', 'return', 'and', 'was', 'who ', 'PVLDB', 'a ', 'the', 'number of ', '@@16@@', 'if ', 'where', '@@18@@', 'how', 'larger than', 'is ', 'from ', 'a', 'for each', 'less', 'are ', '@@19@@', '@@4@@', '@@11@@', 'distinct ', 'to', 'not ', 'me', 'objects', 'with ', ', ', 'lowest', 'in', 'has ', 'zero', 'in ', 'there ', 'lower than', 'highest', '@@9@@', 'than', 'homepage', 'size', 'multiplication', 'with', 'besides ', ',', '@@1@@', 'what', 'have', 'those ', 'of', '@@3@@', 'that', 'there', '@@10@@', '@@5@@', 'both ', '@@15@@', 'number of', 'price', 'any', 'which', 'to ', 'how ', 'when ', 'of ', 'division', 'is', 'homepages', 'or', 'if', 'more', 'sum', '@@12@@', 'smaller than', 'flights', '@@7@@', '@@17@@', 'for each ', 'from', '@@13@@', 'has', 'difference', 'when', 'are', 'any ', '@@8@@', 'both', 'the ', ',  ', 'besides', 'have ', 'where ', 'not']	homepages @@SEP@@ @@1@@ of PVLDB (line number 1)
`

In the .json file for configurations, I have given the path to the '.tsv' file produced after the running the script  'python utils/preprocess_examples.py' as mentioned in the repo.

**Comment by subhashiniy** [comment]
Thanks. When I initiated training using the command: 
`allennlp train seq2seq/train-seq2seq-copynet.json -s ./outputDir`

I am getting the error - 
`python3.6/site-packages/allennlp/data/dataset_readers/copynet_seq2seq.py", line 130, in _read
    raise RuntimeError("Invalid line format: %s (line number %d)" % (line, line_num + 1))
RuntimeError: Invalid line format: return me the homepage of PVLDB . 	['higher than', 'same as', 'what ', 'and ', 'than ', 'at most', 'distinct', 'two', 'at least', 'or ', 'date', 'on ', '@@14@@', 'equal', 'hundred', 'those', 'sorted by', 'elevation', 'which ', '@@6@@', 'was ', 'did ', 'population', 'height', 'one', 'that ', 'on', 'did', 'who', 'true', '@@2@@', '100', 'false', 'return', 'and', 'was', 'who ', 'PVLDB', 'a ', 'the', 'number of ', '@@16@@', 'if ', 'where', '@@18@@', 'how', 'larger than', 'is ', 'from ', 'a', 'for each', 'less', 'are ', '@@19@@', '@@4@@', '@@11@@', 'distinct ', 'to', 'not ', 'me', 'objects', 'with ', ', ', 'lowest', 'in', 'has ', 'zero', 'in ', 'there ', 'lower than', 'highest', '@@9@@', 'than', 'homepage', 'size', 'multiplication', 'with', 'besides ', ',', '@@1@@', 'what', 'have', 'those ', 'of', '@@3@@', 'that', 'there', '@@10@@', '@@5@@', 'both ', '@@15@@', 'number of', 'price', 'any', 'which', 'to ', 'how ', 'when ', 'of ', 'division', 'is', 'homepages', 'or', 'if', 'more', 'sum', '@@12@@', 'smaller than', 'flights', '@@7@@', '@@17@@', 'for each ', 'from', '@@13@@', 'has', 'difference', 'when', 'are', 'any ', '@@8@@', 'both', 'the ', ',  ', 'besides', 'have ', 'where ', 'not']	homepages @@SEP@@ @@1@@ of PVLDB (line number 1)
`

In the .json file for configurations, I have given the path to the '.tsv' (also tried the .json) file produced after the running the script  'python utils/preprocess_examples.py' as mentioned in the repo.

**Comment by mega002** [comment]
It looks like you are feeding copynet the preprocessed `train_lexicon_tokens.json` (train set with lexicon) instead of the preprocessed `train.json` (train set without lexicon).
Copynet doesn't use lexicon, the training data without lexicon should be preprocessed and provided to this model.

**Comment by subhashiniy** [comment]
Sorry to bother you again. But now, after one epoch this error pops up :
`allennlp/models/encoder_decoders/copynet_seq2seq.py", line 272, in _gather_extended_gold_tokens
    first_match = ((matches.cumsum(-1) == 1) * matches).argmax(-1)
RuntimeError: "argmax_cpu" not implemented for 'Bool'`

Could you help me figure this out?
Thanks in advance.

**Comment by mega002** [comment]
Please provide me with more details on your environment (including OS and installed python packages), the command executed, and whether you are running on CPU or GPU.

**Comment by subhashiniy** [comment]
OS : Ubuntu 18.04.3 LTS
Python - 3.6.9
I am running on CPU server only with trainer.cuda_device as -1. 
packages installed - 
`
alabaster==0.7.12
allennlp==0.8.3
attrs==19.3.0
aws-sam-translator==1.22.0
aws-xray-sdk==2.4.3
awscli==1.18.26
Babel==2.8.0
blis==0.2.4
boto==2.49.0
boto3==1.12.26
botocore==1.15.26
certifi==2019.11.28
cffi==1.14.0
cfn-lint==0.29.0
chardet==3.0.4
click==7.1.1
colorama==0.4.3
conllu==0.11
cryptography==2.8
cycler==0.10.0
cymem==2.0.3
decorator==4.4.2
docker==4.2.0
docutils==0.15.2
ecdsa==0.15
edit-distance==1.0.3
editdistance==0.5.3
en-core-web-sm==2.1.0
flaky==3.6.1
Flask==1.1.1
Flask-Cors==3.0.8
ftfy==5.7
future==0.18.2
gevent==1.4.0
greenlet==0.4.15
h5py==2.10.0
idna==2.9
imagesize==1.2.0
importlib-metadata==1.5.0
importlib-resources==1.0.2
itsdangerous==1.1.0
Jinja2==2.11.1
jmespath==0.9.5
joblib==0.14.1
jsondiff==1.1.2
jsonnet==0.15.0
jsonpatch==1.25
jsonpickle==1.3
jsonpointer==2.0
jsonschema==2.6.0
kiwisolver==1.1.0
MarkupSafe==1.1.1
matplotlib==3.2.1
mock==4.0.2
more-itertools==8.2.0
moto==1.3.14
msgpack==0.5.6
murmurhash==1.0.2
networkx==2.3
neuralcoref==4.0
nltk==3.4.5
numpy==1.18.2
numpydoc==0.9.2
overrides==2.8.0
packaging==20.3
pandas==0.24.2
parsimonious==0.8.1
pkg-resources==0.0.0
plac==0.9.6
pluggy==0.13.1
preshed==2.0.1
progressbar==2.5
protobuf==3.11.3
py==1.8.1
pyasn1==0.4.8
pycparser==2.20
Pygments==2.6.1
pyparsing==2.4.6
pytest==5.4.1
python-dateutil==2.8.1
python-jose==3.1.0
pytorch-pretrained-bert==0.6.2
pytz==2019.3
PyYAML==5.3.1
regex==2020.2.20
requests==2.23.0
responses==0.10.12
rsa==3.4.2
s3transfer==0.3.3
scikit-learn==0.22.2.post1
scipy==1.4.1
six==1.14.0
snowballstemmer==2.0.0
spacy==2.1.3
Sphinx==2.4.4
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==1.0.3
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.4
sqlparse==0.3.1
srsly==1.0.2
sshpubkeys==3.1.0
tensorboardX==2.0
thinc==7.0.8
torch==1.4.0
tqdm==4.43.0
Unidecode==1.1.1
urllib3==1.25.8
wasabi==0.6.0
wcwidth==0.1.8
websocket-client==0.57.0
Werkzeug==1.0.0
word2number==1.1
wrapt==1.12.1
xmltodict==0.12.0
zipp==3.1.0
`
Command executed to train : 
`allennlp train seq2seq/train-seq2seq-copynet.json -s ./outputDir`

**Comment by subhashiniy** [comment]
Error traceback: 
`2020-03-23 08:01:59,049 - INFO - allennlp.training.trainer - Epoch 0/24
2020-03-23 08:01:59,050 - INFO - allennlp.training.trainer - Peak CPU memory usage MB: 1035.64
2020-03-23 08:01:59,079 - INFO - allennlp.training.trainer - Training
loss: 89.1837 ||: 100%|##########| 1386/1386 [1:10:41<00:00,  3.06s/it]
2020-03-23 09:12:40,764 - INFO - allennlp.training.trainer - Validating
  0%|          | 0/243 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/user/Break/env/bin/allennlp", line 11, in <module>
    sys.exit(run())
  File "/user/Break/env/lib/python3.6/site-packages/allennlp/run.py", line 18, in run
    main(prog="allennlp")
  File "/user/Break/env/lib/python3.6/site-packages/allennlp/commands/__init__.py", line 101, in main
    args.func(args)
  File "/user/Break/env/lib/python3.6/site-packages/allennlp/commands/train.py", line 103, in train_model_from_args
    args.force)
  File "/user/Break/env/lib/python3.6/site-packages/allennlp/commands/train.py", line 136, in train_model_from_file
    return train_model(params, serialization_dir, file_friendly_logging, recover, force)
  File "/user/Break/env/lib/python3.6/site-packages/allennlp/commands/train.py", line 204, in train_model
    metrics = trainer.train()
  File "/user/Break/env/lib/python3.6/site-packages/allennlp/training/trainer.py", line 493, in train
    val_loss, num_batches = self._validation_loss()
  File "/user/Break/env/lib/python3.6/site-packages/allennlp/training/trainer.py", line 430, in _validation_loss
    loss = self.batch_loss(batch_group, for_training=False)
  File "/user/Break/env/lib/python3.6/site-packages/allennlp/training/trainer.py", line 263, in batch_loss
    output_dict = self.model(**batch)
  File "/user/Break/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/user/Break/env/lib/python3.6/site-packages/allennlp/models/encoder_decoders/copynet_seq2seq.py", line 215, in forward
    target_token_ids)
  File "/user/Break/env/lib/python3.6/site-packages/allennlp/models/encoder_decoders/copynet_seq2seq.py", line 272, in _gather_extended_gold_tokens
    first_match = ((matches.cumsum(-1) == 1) * matches).argmax(-1)
RuntimeError: "argmax_cpu" not implemented for 'Bool'
  0%|          | 0/243 [00:11<?, ?it/s]
`

**Comment by kansalaman** [comment]
> Sorry to bother you again. But now, after one epoch this error pops up :
> INFO - allennlp.training.trainer - Validating
> `allennlp/models/encoder_decoders/copynet_seq2seq.py", line 272, in _gather_extended_gold_tokens first_match = ((matches.cumsum(-1) == 1) * matches).argmax(-1) RuntimeError: "argmax_cpu" not implemented for 'Bool'`
> 
> Could you help me figure this out?
> Thanks in advance.

Got the same error. Changing pytorch version to 1.1.0 removed the error for me.

**Comment by mega002** [comment]
Thanks, @kansalaman .
