### ISSUE TITLE
Error training seq2seq-dynamic

### ISSUE THREAD

**Issue by kansalaman** [tomerwolgithub/Break#6]
While training seq2seq-dynamic using the json file provided (qdmr_parsing/model/seq2seq/train-seq2seq-dynamic.json), I was getting the following error -

`    dataset_reader = DatasetReader.from_params(params.pop('dataset_reader'))
  File "/mnt/blossom/data/amankansal/QA/2020-Hotpot-QA/Break/break_venv/lib/pyth
on3.6/site-packages/allennlp/common/from_params.py", line 275, in from_params
    default_to_first_choice=default_to_first_choice)
  File "/mnt/blossom/data/amankansal/QA/2020-Hotpot-QA/Break/break_venv/lib/pyth
on3.6/site-packages/allennlp/common/params.py", line 334, in pop_choice
    raise ConfigurationError(message)
allennlp.common.checks.ConfigurationError: "seq2seq_dynamic not in acceptable ch
oices for dataset_reader.type: ['ccgbank', 'conll2003', 'conll2000', 'ontonotes_
ner', 'coref', 'winobias', 'event2mind', 'interleaving', 'language_modeling', 'm
ultiprocess', 'ptb_trees', 'drop', 'squad', 'quac', 'triviaqa', 'qangaroo', 'srl
', 'semantic_dependencies', 'seq2seq', 'sequence_tagging', 'snli', 'universal_de
pendencies', 'sst_tokens', 'quora_paraphrase', 'atis', 'nlvr', 'wikitables', 'te
mplate_text2sql', 'grammar_based_text2sql', 'quarel', 'simple_language_modeling'
, 'babi', 'copynet_seq2seq', 'text_classification_json']"
`
The command I used for training - 

`allennlp train model/seq2seq/train-seq2seq-dynamic.json  --serialization-dir checkpoints/seq2seq-dynamic
`
I did change the .tsv files in the json (same as were used in training seq2seq and copynet which worked fine)

Any help would be appreciated. Thanks in advance!

**Comment by mega002** [comment]
Please try adding the following arguments to your command:
`--include-package model.seq2seq.simple_seq2seq_dynamic --include-package dataset_readers.simple_seq2seq_dynamic --include-package model.seq2seq.simple_seq2seq_dynamic_predictor`
