### ISSUE TITLE
Pretrained checkpoints for seq2seq models

### ISSUE THREAD

**Issue by kansalaman** [tomerwolgithub/Break#7]
Can pre-trained models for seq2seq, copynet and seq2seq-dynamic be provided, and also the bleu scores obtained. Just so that we are able to reproduce those and verify our training process.

Thanks in advance!

**Comment by mega002** [comment]
See here:
https://github.com/tomerwolgithub/Break/tree/master/qdmr_parsing#cofiguration-and-petrained-models
