### ISSUE TITLE
Single example prediction for seq2seq-dynamic

### ISSUE THREAD

**Issue by kansalaman** [tomerwolgithub/Break#9]
I want to add the feature of a single example prediction for the seq2seq-dynamic model (mentioned as TODO in run_model.py file). I'd create a pull request once done. Would that be alright/helpful?
In the same context can you please tell how would one get the allowed_tokens for a new question not present in the dataset. Currently, all the questions have allowed_tokens associated with them in the corresponding .json files.
[This is my first ever attempt at contributing to open-source. Please let me know if I am not following appropriate protocol :) ]
Thanks in advance!

**Comment by mega002** [comment]
Sure, @kansalaman , that would be nice, thank you. Please go ahead and create a separate feature branch, once you're done implementing this, open a pull request and assign me as a reviewer.

Regarding `allowed_tokens`, @tomerwolgithub could you please point us to the relevant code?

**Comment by tomerwolgithub** [comment]
Hello @kansalaman , you can find the relevant code is the `valid_annotation_tokens` function, at:
https://github.com/tomerwolgithub/Break/blob/master/annotation_pipeline/utils/app_store_generation.py

**Comment by kansalaman** [comment]
Thanks! I have opened a PR for this. I didn't have enough permissions to assign a reviewer, so I just put a mention over there.

**Comment by zdh2292390** [comment]
> Sure, @kansalaman , that would be nice, thank you. Please go ahead and create a separate feature branch, once you're done implementing this, open a pull request and assign me as a reviewer.
> 
> Regarding `allowed_tokens`, @tomerwolgithub could you please point us to the relevant code?

Hi, @mega002 , could you please provide the pre-trained models or the training code of the seq2seq and copynet? It would be very helpful. Thank you!

**Comment by mega002** [comment]
@zdh2292390 we will publish the trained models soon.
Re training, please check this closed thread #4 .

**Comment by mega002** [comment]
Closing this issue, thanks @kansalaman .
